### ISSUE TITLE
Invalid link on readthedocs

### ISSUE THREAD

**Issue by raczben** [pyvisa/pyvisa-sim#56]
The documentation (https://pyvisa-sim.readthedocs.io/en/latest/) link is invalid.
The Edit on GitHub link points to an invalid file.

**Comment by MatthieuDartiailh** [comment]
I agree that the edit on Github is broken and I will try to have a look. But the link towards RTD works for me.

**Comment by MatthieuDartiailh** [comment]
After rebuilding the docs, it appear the edit on Github link is working again.
