### ISSUE TITLE
Conda installs version 0.3 -- Get no package pyvisa_sim found.

### ISSUE THREAD

**Issue by nate-h** [pyvisa/pyvisa-sim#62]
Hi, would love to use this package.
I'm using python version 3.9 w/ conda.
My env list shows version 0.3 is installed.
When I run:

```py
>>> import pyvisa
>>> pyvisa.ResourceManager("@sim")
```

I get `ValueError: Wrapper not found: No package named pyvisa_sim`

If I uninstall then use pip to install, it downloads version 0.5.1 and that code works.

Any chance this can be fixed? Would love to help if I can.

**Comment by MatthieuDartiailh** [comment]
There is currently no feedstock for pyvisa-sim. You can make a PR to add one and feel free to add me as maintainer.

**Comment by MatthieuDartiailh** [comment]
The issue you opened is in pyvisa-py feedstock we will need a different feedstock for pyvisa-sim.

**Comment by mtsolmn** [comment]
@MatthieuDartiailh this issue can be closed since we've added `pyvisa-sim` to `conda-forge`: https://github.com/conda-forge/pyvisa-sim-feedstock

thanks

**Comment by MatthieuDartiailh** [comment]
Thanks @mtsolmn
